### ISSUE TITLE
希望 feflow init 命令支持传递自定义的配置文件

### ISSUE THREAD

**Issue by helinjiang** [feflow/feflow#12]
在写脚手架时，需要能够传递一个本地的配置文件，例如 webpack 就支持这种命令 `webpack --config webpack.config.js`。

希望能够支持 `feflow init --config ./a/b/c.js` 这种，然后将 `./a/b/c.js` 转换成绝对路径 `/user/a/b/c.js` 传递到 `generator` 脚手架中，由脚手架获得这个文件之后，自行进行处理

**Comment by cpselvis** [comment]
这个现有的 脚手架机制本身就已经支持了。

比如：
``` sh
$ feflow init --name 1  --hello world 
```

![image](https://user-images.githubusercontent.com/18289264/40897649-caabd546-67ee-11e8-99a8-f8a52bb75ee7.png)
