### ISSUE TITLE
feflow 支持本地构建器

### ISSUE THREAD

**Issue by LeoEatle** [feflow/feflow#16]
能否在`feflow.json`中定义
```
builderType: false
```
的时候无需全局安装构建器，而是交给模板里的webpack配置处理。
`feflow dev`运行时可以自动改为运行`npm start`

**Comment by LeoEatle** [comment]
经过讨论，可能改成`feflow eject`这样的形式比较实用

**Comment by cpselvis** [comment]
v0.14.0 版本已经合入了 feflow eject 功能
