### ISSUE TITLE
主机名与RTX名不同导致feflow init失败

### ISSUE THREAD

**Issue by chyingp** [feflow/feflow#18]
### 问题描述

主机名、RTX名不同，导致feflow init过程失败。

### 环境描述：

* osx：10.13.6 (17G65)
* feflow：v0.14.1
* nodejs：v6.14.4

### 重现步骤

1. `feflow init` 之后，选择模板`基于 React + Redux + Webpack 的 web 业务开发解决方案`。
2. 初始化过程的应答：自动申请monitor id、badjs id、离线包、创建 git 项目

**Comment by Stevenzwzhai** [comment]
新版脚手架已经支持手动输入rtx。

**Comment by cpselvis** [comment]
@tencent/generator-now-webpack的v0.3.2版本已支持
