### ISSUE TITLE
未安装脚手架，初次运行feflow init，给出的提示信息不够明确

### ISSUE THREAD

**Issue by chyingp** [feflow/feflow#21]
## For feature request

初次安装feflow-cli，运行`feflow init`，控制台提示如下

```bash
Feflow WARN  检测到你还未安装任何模板，请先安装后再进行项目初始化，参考文档：https://github.com/iv-web/feflow-cli/blob/master/README.md
```

根据提示信息，跳转到 [https://github.com/iv-web/feflow-cli/blob/master/README.md](https://github.com/iv-web/feflow-cli/blob/master/README.md)，并没有任何有用信息

建议：

1. 给出具体的操作指引
2. 提示信息给到的链接，能跳到该指引

**Comment by LeoEatle** [comment]
建议可以加个外部可以使用的generator列表，把这个参考文档链接过去。

或者先直接写上[generator-redux-startkit](https://github.com/feflow/generator-redux-startkit)？

**Comment by cpselvis** [comment]
和这个 issue 重复了：https://github.com/feflow/feflow/issues/46
