### ISSUE TITLE
文档修改建议：脚手架不存在

### ISSUE THREAD

**Issue by chyingp** [feflow/feflow#22]
## For BUG

在文档 [脚手架开发](http://www.feflowjs.org/zh-cn/docs/writing.html) 中，提及 **generator-now-activity**、**generator-now-business** 两个脚手架。

安装的时候提示404。

```
npm install -g generator-now-activity
```

**Comment by LeoEatle** [comment]
这是我们的失误，这两个脚手架目前只在内部npm有发布。之后会修改文档修复这部分。
建议使用https://github.com/feflow/generator-redux-startkit。这是对外的、比较标准的脚手架。

**Comment by LeoEatle** [comment]
#24

**Comment by cpselvis** [comment]
已经处理了，新的文档今天已经发布上去了
