### ISSUE TITLE
windows 下偶发创建项目卡住

### ISSUE THREAD

**Issue by Stevenzwzhai** [feflow/feflow#28]
## For BUG

system: windows10
node: v10.13.0

使用命令feflow init 命令行卡住

**Comment by cpselvis** [comment]
在 windows 下使用 Feflow 初始化项目时卡住的问题已经找到原因了，原因是 Yeoman 运行时在 Node 10.x 版本有 Bug，先使用 Node 6.x 或者 Node 8.x 版本。

**Comment by cpselvis** [comment]
已经向 yeoman 提交 [ISSUE](https://github.com/yeoman/environment/issues/109)，我们先尝试修复，修复成功后提交PR给Yeoman

**Comment by cpselvis** [comment]
已经Fix，在v0.15.1版本修复了这个问题，对应的 Commit是：https://github.com/feflow/feflow/pull/38
