### ISSUE TITLE
建议构建器支持生产环境开启sourcemap生成

### ISSUE THREAD

**Issue by Vincentway** [feflow/feflow#55]
监控上报系统如`badjs`、`sentry`可以支持`sourcemap`还原报错代码位置，但需要将编译生成的`sourcemap`文件上传至监控系统服务器。
所以希望`feflow`增加一个配置项允许开启生产环境生成`sourcemap`，满足上述需求。

**Comment by cpselvis** [comment]
这个转移到构建器的 issue 进行跟进：https://github.com/feflow/feflow/issues/55
